version: '3'
services:
  popcorn:
    build: .
    ports:
      - 8888:8888
    volumes:
      - "./:/app"
    command: bash -c "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root"
    restart: always
